name: Coucou cron ðŸ‘‹

on:
  schedule:
    # Tous les jours Ã  9h UTC
    - cron: '*/10 * * * *'

  # Utile pour pouvoir le lancer Ã  la main depuis GitHub
  workflow_dispatch:

jobs:
  dire-coucou:
    runs-on: ubuntu-latest

    steps:
      - name: Dire coucou et donner l'heure
        run: |
          echo "ðŸ‘‹ Coucou !"
          echo "ðŸ•’ Il est actuellement :"
          date
